version: '2'
services:
  kibana:
    image: duizhang/kibana:5.1.2
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://{{groups['elasticsearch-servers'][0]}}:9200
