---
- name: "Make sure /opt/kibana"
  file: path=/opt/kibana state=directory

- name: "upload kibana docker-compose file"
  template: src=kibana-docker-compose.yml dest=/opt/kibana/docker-compose.yml

- name: "install kibana service"
  copy: src=kibana.service dest=/etc/systemd/system/kibana.service

- name: start kibana service
  systemd:
    name: kibana
    daemon_reload: yes
    state: restarted
    enabled: yes
